# Generated by Django 2.2.10 on 2020-09-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_fkitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fkitem',
            new_name='title',
        ),
    ]
