# Generated by Django 2.2.10 on 2020-09-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200901_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.ManyToManyField(to='core.Item'),
        ),
    ]
