# Generated by Django 2.2.10 on 2020-09-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
    ]
