# Generated by Django 2.2.9 on 2020-09-06 06:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_order_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='phone_no',
            field=models.CharField(default='1234567890', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone', to='core.BillingAddress'),
        ),
        migrations.AddField(
            model_name='item',
            name='shop_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Shop'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Shop'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shop_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Shop'),
        ),
    ]
