# Generated by Django 2.2.9 on 2020-09-06 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200906_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shop_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Shop'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shop_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Shop'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shop_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Shop'),
        ),
    ]
