# Generated by Django 2.2.9 on 2020-09-06 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200906_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='shop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Shop'),
        ),
    ]
