# Generated by Django 2.2.9 on 2020-09-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_shop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='items',
            field=models.ManyToManyField(to='core.OrderItem'),
        ),
    ]
