# Generated by Django 2.2.9 on 2020-09-07 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='is_active',
        ),
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(default='amir'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ServicesPeoples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_given', models.TextField()),
                ('service_description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Services')),
            ],
        ),
    ]
