# Generated by Django 2.2.9 on 2020-09-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200907_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicespeoples',
            name='service',
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='ServicesPeoples',
        ),
    ]
