# Generated by Django 2.2.9 on 2020-09-09 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200907_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='phone_no',
        ),
    ]
