# Generated by Django 2.2.9 on 2020-09-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200909_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='country',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='Phone_number',
            field=models.IntegerField(default='1234567890'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='first_name',
            field=models.CharField(default='axon', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='last_name',
            field=models.CharField(default='allen', max_length=100),
            preserve_default=False,
        ),
    ]
