# Generated by Django 2.2.9 on 2020-09-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200909_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name_plural': 'Address'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
    ]
