# Generated by Django 2.2.9 on 2020-09-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200909_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='zip',
            new_name='Pin_Code',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='last_name',
        ),
    ]
